You can write controllers that support https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events[Server Sent Events] using the RxJava plugin for Grails.

Using the link:groovydoc/grails/rx/web/helper/RxHelper.html#stream(Observable<T>,%20java.lang.Long,%20java.util.concurrent.TimeUnit)[stream] method you can return an observable that streams events to the browser.

For example:

[source,groovy]
----
def index() {

    rx.stream { rx.Observer observer -> <1>
       for(i in (0..5)) {
           if(i % 2 == 0) {
               observer.onNext(
                   rx.render("Tick") <2>
               )
           }
           else {
               observer.onNext(
                   rx.render("Tock")
               )

           }
           sleep 1000 <3>
       }
       subscriber.onCompleted() <4>
   }
}
----

<1> Call the `stream` method passing a closure that accepts an `rx.Observer` to start sending events
<2> Emit a one or many items using `onNext`
<3> Call `sleep` to simulate a slow request
<4> Call `onCompleted` to complete the request


The above example is a simple example that simulates a process that takes a while using the `sleep` method, alternating the words "Tick" and "Tock".

On the client side you can register a JavaScript function that uses the controller as an event source:

[source,javascript]
----
function tickTock() {
    var eventSource = new EventSource("ticktock");
    eventSource.onmessage = function(event) {
        console.log("data: "+event.data)
        document.getElementById('message').innerHTML = event.data;
    };

}
tickTock()
----

NOTE: The `EventSource` object is supported in http://caniuse.com/#feat=eventsource[most modern browsers], except Internet Explorer. You can use https://github.com/remy/polyfills/blob/master/EventSource.js[polyfills JavaScript] replacement for IE.


In the above example the `onmessage` handler will be invoked every time an item is emitted.

If you wish to send a particular named event you can use the name argument of the `stream` method:

[source,groovy]
----
stream "ticktock", { rx.Observer observer ->
----

And then attach an event listener for only that event on the client:

[source,javascript]
----
function tickTock() {
    var eventSource = new EventSource("ticktock");
    eventSource.addEventListener('ticktock', function(event) {
        console.log("data: "+event.data)
        document.getElementById('message').innerHTML = event.data;
    }, false);
}
----

In addition for more complex event types you can use the `rx.event` method:

[source,groovy]
----
    rx.stream { rx.Observer observer ->
       for(i in (0..5)) {
           if(i % 2 == 0) {
               observer.onNext(
                   rx.event("Tick", event:"Event $i", id:"$id", comment:"Tick Event") <1>
               )
           }
           else {
                ...
           }
       }
       ...
   }
----

<1> The `event` method can be used to customize the Server Sent event properties and rendering multi-line data.

The `event` method also accepts `Writable` instances, which can be useful in combination with builders:

[source,groovy]
----
Writable writable = new Writable() {
   @Override
    Writer writeTo(Writer writer) throws IOException {
        new StreamingJsonBuilder(writer).call {
            tick "Tock"
        }
        return writer
    }
}
rx.event(writable, event:"Event $i", id:"$id", comment:"Tick Event")

----