You can write controllers that support https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events[Server Sent Events] using the RxJava plugin for Grails.

Using the link:groovydoc/grails/rx/web/helper/RxHelper.html#stream(Observable<T>,%20java.lang.Long,%20java.util.concurrent.TimeUnit)[stream] method you can return an observable that streams events to the browser.

For example:

[source,groovy]
----
def index() {

    rx.stream { Subscriber subscriber -> <1>
       for(i in (0..5)) {
           if(i % 2 == 0) {
               subscriber.onNext(
                   rx.render("Tick") <2>
               )
           }
           else {
               subscriber.onNext(
                   rx.render("Tock")
               )

           }
           sleep 1000 <3>
       }
       subscriber.onCompleted() <4>
   } <5>
}
----

<1> Call the `stream` method passing a closure that accepts an `rx.Subscriber` to start sending events
<2> Emit a new item from the `Observable` using `onNext`
<3> Call `sleep` to simulate a slow request
<4> Call `onCompleted` to complete the request


The above example is a simple example that simulates a process that takes a while using the `sleep` method, alternating the words "Tick" and "Tock".

On the client side you can register a JavaScript function that uses the controller as an event source:

[source,javascript]
----
function tickTock() {
    var eventSource = new EventSource("ticktock");
    eventSource.onmessage = function(event) {
        console.log("data: "+event.data)
        document.getElementById('message').innerHTML = event.data;
    };

}
tickTock()
----

In the above exmple the `onmessage` handler will be invoked every time the `Observable` emits an item.

If you wish to send a particular named event you can use the name argument of the `stream` method:

[source,groovy]
----
stream "ticktock", { Subscriber subscriber ->
----

And then attach an event listener for only that event on the client:

[source,javascript]
----
function tickTock() {
    var eventSource = new EventSource("ticktock");
    eventSource.addEventListener('ticktock', function(event) {
        console.log("data: "+event.data)
        document.getElementById('message').innerHTML = event.data;
    }, false);
}
----